---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-springboot-gradle
spec:
  destination:
    name: ''
    namespace: sample-projects
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/java-springboot-gradle
    repoURL: 'https://github.com/srajasimman/sample-projects.git'
    targetRevision: java-springboot-gradle
    helm:
      parameters:
        - name: 'ingress.hosts[0].host'
          value: java-springboot-gradle.10-10-30-68.sslip.io
        - name: ingress.enabled
          value: 'true'
        - name: ingress.className
          value: nginx
        - name: 'ingress.hosts[0].paths[0].path'
          value: /
        - name: 'ingress.hosts[0].paths[0].pathType'
          value: ImplementationSpecific
        - name: metrics.serviceMonitor.enabled
          value: 'true'
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-springboot-maven
spec:
  destination:
    name: ''
    namespace: sample-projects
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/java-springboot-maven
    repoURL: 'https://github.com/srajasimman/sample-projects.git'
    targetRevision: java-springboot-maven
    helm:
      parameters:
        - name: 'ingress.hosts[0].host'
          value: java-springboot-maven.10-10-30-68.sslip.io
        - name: ingress.enabled
          value: 'true'
        - name: ingress.className
          value: nginx
        - name: 'ingress.hosts[0].paths[0].path'
          value: /
        - name: 'ingress.hosts[0].paths[0].pathType'
          value: ImplementationSpecific
        - name: metrics.serviceMonitor.enabled
          value: 'true'
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-flask-webapp
spec:
  destination:
    name: ''
    namespace: sample-projects
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/python-flask-webapp
    repoURL: 'https://github.com/srajasimman/sample-projects.git'
    targetRevision: python-flask-webapp
    helm:
      parameters:
        - name: 'ingress.hosts[0].host'
          value: python-flask-webapp.10-10-30-68.sslip.io
        - name: ingress.enabled
          value: 'true'
        - name: ingress.className
          value: nginx
        - name: 'ingress.hosts[0].paths[0].path'
          value: /
        - name: 'ingress.hosts[0].paths[0].pathType'
          value: ImplementationSpecific
        - name: metrics.serviceMonitor.enabled
          value: 'true'
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: javascript-nodejs-expressjs
spec:
  destination:
    name: ''
    namespace: sample-projects
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/javascript-nodejs-expressjs
    repoURL: 'https://github.com/srajasimman/sample-projects.git'
    targetRevision: javascript-nodejs-expressjs
    helm:
      parameters:
        - name: 'ingress.hosts[0].host'
          value: javascript-nodejs-expressjs.10-10-30-68.sslip.io
        - name: ingress.enabled
          value: 'true'
        - name: ingress.className
          value: nginx
        - name: 'ingress.hosts[0].paths[0].path'
          value: /
        - name: 'ingress.hosts[0].paths[0].pathType'
          value: ImplementationSpecific
        - name: metrics.serviceMonitor.enabled
          value: 'true'
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
